### ISSUE TITLE
Support ENV variables/states

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/colabo#317] opened 2018-09-11 09:53 UTC
[ September 11, 2018 11:48 ] Sasa Rudan: I'ma ENV servis, Koji ucitava JSON ili J's fajl is config/config.js muslim
[ September 11, 2018 11:49 ] Sasa Rudan: To jeradilo na ng1 I tamo su bill podaci o server it'd, najbolji nqcin po meni
Ne znam da li Sam prebacio na Novi Ali mogu to odraditi Dana's/sutra

**Approaches:**
- **so far, I made it like this**: https://stackoverflow.com/questions/43193049/app-settings-the-angular-way
- https://stackoverflow.com/questions/34986922/define-global-constants-in-angular-2/43439599#43439599

**Comment by mprinc** [comment] 2018-09-19 09:57
Duplicate of #320

**Closed by mprinc** 2018-09-19 09:57 UTC
Labels: NON URGENT.NICE TO HAVE
